## Deliverable 2. Create a Customer Travel Destinations Map.

In [14]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [15]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Massakory,TD,12.9960,15.7293,80.11,73,39,6.98,light rain,2021-08-07 20:28:00
1,1,Rikitea,PF,-23.1203,-134.9692,74.01,80,11,12.33,few clouds,2021-08-07 20:24:49
2,2,Mataura,NZ,-46.1927,168.8643,35.47,99,100,0.94,overcast clouds,2021-08-07 20:28:00
3,3,Talnakh,RU,69.4865,88.3972,55.18,60,10,3.96,clear sky,2021-08-07 20:24:43
4,4,Upernavik,GL,72.7868,-56.1549,40.86,95,100,9.15,overcast clouds,2021-08-07 20:28:00

In [7]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you are looking for on your trip? "))
max_temp = float(input("What is the maximum temperature you are looking for on your trip? "))

What is the minimum temperature you are looking for on your trip? 65
What is the maximum temperature you are looking for on your trip? 75

In [8]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
1,1,Rikitea,PF,-23.1203,-134.9692,74.01,80,11,12.33,few clouds,2021-08-07 20:24:49
10,10,Ocampo,MX,21.6500,-101.5000,71.74,51,28,12.62,scattered clouds,2021-08-07 20:28:01
16,16,Kurchum,KZ,48.5722,83.6542,65.37,45,93,4.97,overcast clouds,2021-08-07 20:28:02
23,23,Hanzhong,CN,33.0728,107.0303,68.45,92,100,1.19,light rain,2021-08-07 20:28:04
25,25,Vaini,TO,-21.2000,-175.2000,68.16,77,40,5.75,scattered clouds,2021-08-07 20:28:05
31,31,Ponta Delgada,PT,37.7333,-25.6667,70.52,64,75,6.91,broken clouds,2021-08-07 20:28:06
33,33,Miri,MY,4.4148,114.0089,73.54,100,40,11.50,heavy intensity rain,2021-08-07 20:26:03
35,35,Saint-Philippe,RE,-21.3585,55.7679,71.15,77,37,12.06,scattered clouds,2021-08-07 20:28:07
57,57,Vao,NC,-22.6667,167.4833,67.23,65,100,7.58,overcast clouds,2021-08-07 20:28:10
58,58,Port Moresby,PG,-9.4431,147.1797,74.62,88,75,11.50,broken clouds,2021-08-07 20:25:42

In [9]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                151
City                   151
Country                150
Lat                    151
Lng                    151
Max Temp               151
Humidity               151
Cloudiness             151
Wind Speed             151
Current Description    151
Date                   151
dtype: int64

In [10]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_final_df = preferred_cities_df.dropna()
preferred_cities_final_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
1,1,Rikitea,PF,-23.1203,-134.9692,74.01,80,11,12.33,few clouds,2021-08-07 20:24:49
10,10,Ocampo,MX,21.6500,-101.5000,71.74,51,28,12.62,scattered clouds,2021-08-07 20:28:01
16,16,Kurchum,KZ,48.5722,83.6542,65.37,45,93,4.97,overcast clouds,2021-08-07 20:28:02
23,23,Hanzhong,CN,33.0728,107.0303,68.45,92,100,1.19,light rain,2021-08-07 20:28:04
25,25,Vaini,TO,-21.2000,-175.2000,68.16,77,40,5.75,scattered clouds,2021-08-07 20:28:05
...,...,...,...,...,...,...,...,...,...,...,...
688,688,Grand Gaube,MU,-20.0064,57.6608,70.38,74,33,1.99,light rain,2021-08-07 20:27:01
692,692,Kemin,KG,42.7846,75.6892,67.14,34,23,5.82,few clouds,2021-08-07 20:31:02
693,693,Vrangel,RU,42.7297,133.0839,69.58,93,43,8.12,scattered clouds,2021-08-07 20:31:02
713,713,Ipameri,BR,-17.7219,-48.1597,70.12,42,90,6.71,overcast clouds,2021-08-07 20:31:08
715,715,Kamina,CD,-8.7386,24.9906,66.31,26,82,4.00,broken clouds,2021-08-07 20:31:08

In [11]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_final_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Rikitea,PF,74.01,few clouds,-23.1203,-134.9692,
10,Ocampo,MX,71.74,scattered clouds,21.6500,-101.5000,
16,Kurchum,KZ,65.37,overcast clouds,48.5722,83.6542,
23,Hanzhong,CN,68.45,light rain,33.0728,107.0303,
25,Vaini,TO,68.16,scattered clouds,-21.2000,-175.2000,
31,Ponta Delgada,PT,70.52,broken clouds,37.7333,-25.6667,
33,Miri,MY,73.54,heavy intensity rain,4.4148,114.0089,
35,Saint-Philippe,RE,71.15,scattered clouds,-21.3585,55.7679,
57,Vao,NC,67.23,overcast clouds,-22.6667,167.4833,
58,Port Moresby,PG,74.62,broken clouds,-9.4431,147.1797,

In [16]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]    
    
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        hotel_df.loc[index, "Hotel Name"] = np.nan
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [17]:
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Rikitea,PF,74.01,few clouds,-23.1203,-134.9692,People ThankYou
10,Ocampo,MX,71.74,scattered clouds,21.6500,-101.5000,Casa de ratas
16,Kurchum,KZ,65.37,overcast clouds,48.5722,83.6542,"Gostinitsa ""Kneda"""
23,Hanzhong,CN,68.45,light rain,33.0728,107.0303,Guorui Hotel
25,Vaini,TO,68.16,scattered clouds,-21.2000,-175.2000,Keleti Beach Resort

In [18]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.count()

City                   150
Country                150
Max Temp               150
Current Description    150
Lat                    150
Lng                    150
Hotel Name             132
dtype: int64

In [20]:
# Removing Hotels with null values
clean_hotel_df = hotel_df.dropna()
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Rikitea,PF,74.01,few clouds,-23.1203,-134.9692,People ThankYou
10,Ocampo,MX,71.74,scattered clouds,21.6500,-101.5000,Casa de ratas
16,Kurchum,KZ,65.37,overcast clouds,48.5722,83.6542,"Gostinitsa ""Kneda"""
23,Hanzhong,CN,68.45,light rain,33.0728,107.0303,Guorui Hotel
25,Vaini,TO,68.16,scattered clouds,-21.2000,-175.2000,Keleti Beach Resort
31,Ponta Delgada,PT,70.52,broken clouds,37.7333,-25.6667,Vila Nova Hotel
33,Miri,MY,73.54,heavy intensity rain,4.4148,114.0089,"Mega Hotel, Miri"
35,Saint-Philippe,RE,71.15,scattered clouds,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
57,Vao,NC,67.23,overcast clouds,-22.6667,167.4833,Hotel Kou-Bugny
58,Port Moresby,PG,74.62,broken clouds,-9.4431,147.1797,Lamana Hotel (Port Moresby)

In [21]:
# 8a. Create the output File (CSV)
output_data_file="WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [22]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [23]:
# 11a. Add a marker layer for each city to the map. 
locations = clean_hotel_df[["Lat", "Lng"]]
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))